# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/lab7_1_provided_fa24/mb_usb_hdmi_top.xdc

# Block Designs: bd/mb_block/mb_block.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block || ORIG_REF_NAME==mb_block} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_microblaze_0_2/mb_block_microblaze_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_microblaze_0_2 || ORIG_REF_NAME==mb_block_microblaze_0_2} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_dlmb_v10_2/mb_block_dlmb_v10_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_dlmb_v10_2 || ORIG_REF_NAME==mb_block_dlmb_v10_2} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_ilmb_v10_2/mb_block_ilmb_v10_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_ilmb_v10_2 || ORIG_REF_NAME==mb_block_ilmb_v10_2} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_dlmb_bram_if_cntlr_2/mb_block_dlmb_bram_if_cntlr_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_dlmb_bram_if_cntlr_2 || ORIG_REF_NAME==mb_block_dlmb_bram_if_cntlr_2} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_ilmb_bram_if_cntlr_2/mb_block_ilmb_bram_if_cntlr_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_ilmb_bram_if_cntlr_2 || ORIG_REF_NAME==mb_block_ilmb_bram_if_cntlr_2} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_lmb_bram_2/mb_block_lmb_bram_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_lmb_bram_2 || ORIG_REF_NAME==mb_block_lmb_bram_2} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_xbar_1/mb_block_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_xbar_1 || ORIG_REF_NAME==mb_block_xbar_1} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_microblaze_0_axi_periph_1/mb_block_microblaze_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_microblaze_0_axi_periph_1 || ORIG_REF_NAME==mb_block_microblaze_0_axi_periph_1} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_microblaze_0_axi_intc_1/mb_block_microblaze_0_axi_intc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_microblaze_0_axi_intc_1 || ORIG_REF_NAME==mb_block_microblaze_0_axi_intc_1} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_mdm_1_2/mb_block_mdm_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_mdm_1_2 || ORIG_REF_NAME==mb_block_mdm_1_2} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_clk_wiz_1_2/mb_block_clk_wiz_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_clk_wiz_1_2 || ORIG_REF_NAME==mb_block_clk_wiz_1_2} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_rst_clk_wiz_1_100M_2/mb_block_rst_clk_wiz_1_100M_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_rst_clk_wiz_1_100M_2 || ORIG_REF_NAME==mb_block_rst_clk_wiz_1_100M_2} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_axi_uartlite_0_1/mb_block_axi_uartlite_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_axi_uartlite_0_1 || ORIG_REF_NAME==mb_block_axi_uartlite_0_1} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_hdmi_text_controller_0_1/mb_block_hdmi_text_controller_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_hdmi_text_controller_0_1 || ORIG_REF_NAME==mb_block_hdmi_text_controller_0_1} -quiet] -quiet

# XDC: c:/Users/steff/Downloads/ece385git/lab71/lab71.gen/sources_1/bd/mb_block/mb_block_ooc.xdc
