# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/steff/OneDrive/Documents/ECE385/ip_repo/edit_hdmi_packman_controller_v1_0.srcs/sources_1/ip/ghosts_rom/ghosts_rom.xci
# IP: The module: 'ghosts_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/steff/OneDrive/Documents/ECE385/ip_repo/edit_hdmi_packman_controller_v1_0.gen/sources_1/ip/ghosts_rom/ghosts_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ghosts_rom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/steff/OneDrive/Documents/ECE385/ip_repo/edit_hdmi_packman_controller_v1_0.srcs/sources_1/ip/ghosts_rom/ghosts_rom.xci
# IP: The module: 'ghosts_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/steff/OneDrive/Documents/ECE385/ip_repo/edit_hdmi_packman_controller_v1_0.gen/sources_1/ip/ghosts_rom/ghosts_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ghosts_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
