# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/steff/OneDrive/Documents/ECE385/ip_repo/hdmi_packman_controller_1_0/src/board_rom/board_rom.xci
# IP: The module: 'board_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/steff/OneDrive/Documents/ECE385/ip_repo/hdmi_packman_controller_1_0/src/board_rom/board_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'board_rom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/steff/OneDrive/Documents/ECE385/ip_repo/hdmi_packman_controller_1_0/src/board_rom/board_rom.xci
# IP: The module: 'board_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/steff/OneDrive/Documents/ECE385/ip_repo/hdmi_packman_controller_1_0/src/board_rom/board_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'board_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
