# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/steff/Downloads/ece385git/lab71/lab71.srcs/sources_1/bd/mb_block/ip/mb_block_clk_wiz_1_2/mb_block_clk_wiz_1_2.xci
# IP: The module: 'mb_block_clk_wiz_1_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/steff/Downloads/ece385git/lab71/lab71.gen/sources_1/bd/mb_block/ip/mb_block_clk_wiz_1_2/mb_block_clk_wiz_1_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_clk_wiz_1_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/steff/Downloads/ece385git/lab71/lab71.gen/sources_1/bd/mb_block/ip/mb_block_clk_wiz_1_2/mb_block_clk_wiz_1_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_clk_wiz_1_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/steff/Downloads/ece385git/lab71/lab71.gen/sources_1/bd/mb_block/ip/mb_block_clk_wiz_1_2/mb_block_clk_wiz_1_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_clk_wiz_1_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/steff/Downloads/ece385git/lab71/lab71.srcs/sources_1/bd/mb_block/ip/mb_block_clk_wiz_1_2/mb_block_clk_wiz_1_2.xci
# IP: The module: 'mb_block_clk_wiz_1_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/steff/Downloads/ece385git/lab71/lab71.gen/sources_1/bd/mb_block/ip/mb_block_clk_wiz_1_2/mb_block_clk_wiz_1_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_clk_wiz_1_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/steff/Downloads/ece385git/lab71/lab71.gen/sources_1/bd/mb_block/ip/mb_block_clk_wiz_1_2/mb_block_clk_wiz_1_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_clk_wiz_1_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/steff/Downloads/ece385git/lab71/lab71.gen/sources_1/bd/mb_block/ip/mb_block_clk_wiz_1_2/mb_block_clk_wiz_1_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_clk_wiz_1_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
