# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/steff/Downloads/ece385git/ip_repo/hdmi_text_controller_1_0/src/clk_wiz_0_1/clk_wiz_0.xci
# IP: The module: 'clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/steff/Downloads/ece385git/ip_repo/hdmi_text_controller_1_0/src/clk_wiz_0_1/clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/steff/Downloads/ece385git/ip_repo/hdmi_text_controller_1_0/src/clk_wiz_0_1/clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/steff/Downloads/ece385git/ip_repo/hdmi_text_controller_1_0/src/clk_wiz_0_1/clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/steff/Downloads/ece385git/ip_repo/hdmi_text_controller_1_0/src/clk_wiz_0_1/clk_wiz_0.xci
# IP: The module: 'clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/steff/Downloads/ece385git/ip_repo/hdmi_text_controller_1_0/src/clk_wiz_0_1/clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/steff/Downloads/ece385git/ip_repo/hdmi_text_controller_1_0/src/clk_wiz_0_1/clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/steff/Downloads/ece385git/ip_repo/hdmi_text_controller_1_0/src/clk_wiz_0_1/clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
