# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/steff/OneDrive/Documents/ECE385/packman/packman.srcs/sources_1/bd/mb_block/ip/mb_block_hdmi_packman_control_0_0/mb_block_hdmi_packman_control_0_0.xci
# IP: The module: 'mb_block_hdmi_packman_control_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/steff/OneDrive/Documents/ECE385/packman/packman.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_packman_control_0_0/src/hdmi_tx_0/hdmi_tx_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_tx_0 || ORIG_REF_NAME==hdmi_tx_0} -quiet] -quiet

# IP: c:/Users/steff/OneDrive/Documents/ECE385/packman/packman.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_packman_control_0_0/src/clk_wiz_0/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# IP: c:/Users/steff/OneDrive/Documents/ECE385/packman/packman.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_packman_control_0_0/src/board_rom/board_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==board_rom || ORIG_REF_NAME==board_rom} -quiet] -quiet

# IP: c:/Users/steff/OneDrive/Documents/ECE385/packman/packman.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_packman_control_0_0/src/pm_rom/pm_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pm_rom || ORIG_REF_NAME==pm_rom} -quiet] -quiet

# XDC: c:/Users/steff/OneDrive/Documents/ECE385/packman/packman.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_packman_control_0_0/src/clk_wiz_0/clk_wiz_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/steff/OneDrive/Documents/ECE385/packman/packman.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_packman_control_0_0/src/clk_wiz_0/clk_wiz_0_ooc.xdc

# XDC: c:/Users/steff/OneDrive/Documents/ECE385/packman/packman.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_packman_control_0_0/src/board_rom/board_rom_ooc.xdc

# XDC: c:/Users/steff/OneDrive/Documents/ECE385/packman/packman.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_packman_control_0_0/src/pm_rom/pm_rom_ooc.xdc

# IP: C:/Users/steff/OneDrive/Documents/ECE385/packman/packman.srcs/sources_1/bd/mb_block/ip/mb_block_hdmi_packman_control_0_0/mb_block_hdmi_packman_control_0_0.xci
# IP: The module: 'mb_block_hdmi_packman_control_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/steff/OneDrive/Documents/ECE385/packman/packman.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_packman_control_0_0/src/hdmi_tx_0/hdmi_tx_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_tx_0 || ORIG_REF_NAME==hdmi_tx_0} -quiet] -quiet

# IP: c:/Users/steff/OneDrive/Documents/ECE385/packman/packman.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_packman_control_0_0/src/clk_wiz_0/clk_wiz_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# IP: c:/Users/steff/OneDrive/Documents/ECE385/packman/packman.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_packman_control_0_0/src/board_rom/board_rom.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==board_rom || ORIG_REF_NAME==board_rom} -quiet] -quiet

# IP: c:/Users/steff/OneDrive/Documents/ECE385/packman/packman.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_packman_control_0_0/src/pm_rom/pm_rom.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pm_rom || ORIG_REF_NAME==pm_rom} -quiet] -quiet

# XDC: c:/Users/steff/OneDrive/Documents/ECE385/packman/packman.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_packman_control_0_0/src/clk_wiz_0/clk_wiz_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/steff/OneDrive/Documents/ECE385/packman/packman.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_packman_control_0_0/src/clk_wiz_0/clk_wiz_0_ooc.xdc

# XDC: c:/Users/steff/OneDrive/Documents/ECE385/packman/packman.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_packman_control_0_0/src/board_rom/board_rom_ooc.xdc

# XDC: c:/Users/steff/OneDrive/Documents/ECE385/packman/packman.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_packman_control_0_0/src/pm_rom/pm_rom_ooc.xdc
